name: Create Rust Release
# This workflow will create a new tag and release and upload the binary named 'my-binary' to the release on every push to main

on:
  push:
    branches:
    - main
    files:
    - 'Cargo.toml'

permissions: # these permissions are required for the actions to run
  contents: write

jobs:
  auto-release: # this job will create a new tag and release
    uses: init4tech/actions/.github/workflows/auto-release.yml@main
    with:
      binary-name: 'my-binary' # the name of the binary that will be used for versioning the release
