name: CI
on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  solidity-base:
    uses: init4tech/actions/.github/workflows/solidity-base.yml@main
    with:
      disable-gas-snapshot: true # optional param, disables gas snapshot
