name: add binaries to release
on:
  push:
    tags:
    - 'v*'
    # this will trigger anytime a tag is pushed matching the regex v* (v1.0.0, v2.0.0, etc.)

permissions:
  contents: write

# uploads the bins to a newly created release (denoted by the tag v* that was pushed)
jobs:
  upload-binaries:
    uses: init4tech/actions/.github/workflows/release-crates.yml@main
    with:
      binary-name: 'my-binary'
