name: CI
on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  solidity-base:
    uses: init4tech/actions/.github/workflows/solidity-base.yml@main
    with:
      gas-diff-tolerance: 2 # example of optional param, allows 2% tolerance in the diff
