name: Release Crates
on:
  workflow_call:

permissions:
    contents: write    

jobs:
    release_crates:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install Rust toolchain
          uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2  
        - name: Cargo Build Release
          run: cargo build --release
        - name: Cargo Package
          run: cargo package --allow-dirty
        - name: Publish to Crates.io
          run: cargo publish
          env:
            CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
                