name: 'Rust Library Base CI'
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  rust-base-checks:
    name: Base Checks
    uses: init4tech/actions/.github/workflows/rust-base.yml


  feature-checks:
    name: Feature Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
      - run: cargo clippy --all-targets --all-features
      - run: cargo clippy --all-targets --no-default-features
